[target.aarch64-unknown-linux-ohos]
ar = "/data/bin/sdk/linux/native/llvm/bin/llvm-ar"
linker = "/data/bin/sdk/linux/native/llvm/bin/aarch64-linux-ohos-clang"

[target.armv7-unknown-linux-ohos]
ar = "/data/bin/sdk/linux/native/llvm/bin/llvm-ar"
linker = "/data/bin/sdk/linux/native/llvm/bin/arm-linux-ohos-clang"
